version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ./:/app
    ports:
      - ${DEV_PORT}:3000

  nginx:
    image: nginx:alpine
    tty: true
    restart: unless-stopped
    volumes:
      - ${FRONTEND_PATH_HOST}:/var/www/frontend/
      - ${NGINX_PATH_HOST}/conf.d:/etc/nginx/conf.d/
      - ${NGINX_PATH_HOST}/log/:/var/log/nginx/
    ports:
      - ${WEB_HTTP_PORT}:80


networks:
  app-network:
    driver: bridge